### ISSUE TITLE
 regex for datetime

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#48] opened 2018-11-27 18:24 UTC
From [extra-validation-items-description_domain.md](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-description_domain.md) 
> xref.access_time regex for date-time but this maybe already validated in first level

[ ] investigate if/how the date-time is validated

**Comment by mr-c** [comment] 2018-11-28 07:11
@HadleyKing duplicate of which issue? The closest I could find is https://github.com/biocompute-objects/BCO_Specification/issues/49 which was made after this issue

**Closed** 2018-12-06 17:36 UTC
Labels: todo
